version: '3.8'

services:
  mortgage-calculator:
    image: mortgage-calculator
    container_name: mortgage-calculator
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "4000:8080"
    env_file:
      - .env